/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace NebulaBallot {
  export type ProposalStruct = { name: string; voteCount: BigNumberish };

  export type ProposalStructOutput = [name: string, voteCount: bigint] & {
    name: string;
    voteCount: bigint;
  };
}

export interface NebulaBallotInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "chairperson"
      | "delegate"
      | "getProposal"
      | "getProposals"
      | "getVoter"
      | "giveRightToVote"
      | "proposalsCount"
      | "vote"
      | "voters"
      | "winnerName"
      | "winnerProposal"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "RightGranted" | "VoteDelegated" | "Voted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "chairperson",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "delegate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVoter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "giveRightToVote",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposalsCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "vote", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "voters", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "winnerName",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "winnerProposal",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "chairperson",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "delegate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVoter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "giveRightToVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposalsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "voters", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "winnerName", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "winnerProposal",
    data: BytesLike
  ): Result;
}

export namespace RightGrantedEvent {
  export type InputTuple = [voter: AddressLike, weight: BigNumberish];
  export type OutputTuple = [voter: string, weight: bigint];
  export interface OutputObject {
    voter: string;
    weight: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteDelegatedEvent {
  export type InputTuple = [from: AddressLike, to: AddressLike];
  export type OutputTuple = [from: string, to: string];
  export interface OutputObject {
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotedEvent {
  export type InputTuple = [
    voter: AddressLike,
    proposal: BigNumberish,
    weight: BigNumberish
  ];
  export type OutputTuple = [voter: string, proposal: bigint, weight: bigint];
  export interface OutputObject {
    voter: string;
    proposal: bigint;
    weight: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NebulaBallot extends BaseContract {
  connect(runner?: ContractRunner | null): NebulaBallot;
  waitForDeployment(): Promise<this>;

  interface: NebulaBallotInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  chairperson: TypedContractMethod<[], [string], "view">;

  delegate: TypedContractMethod<[to: AddressLike], [void], "nonpayable">;

  getProposal: TypedContractMethod<
    [index: BigNumberish],
    [[string, bigint] & { name: string; voteCount: bigint }],
    "view"
  >;

  getProposals: TypedContractMethod<
    [],
    [NebulaBallot.ProposalStructOutput[]],
    "view"
  >;

  getVoter: TypedContractMethod<
    [account: AddressLike],
    [
      [bigint, boolean, string, bigint] & {
        weight: bigint;
        voted: boolean;
        delegateAddr: string;
        votedProposal: bigint;
      }
    ],
    "view"
  >;

  giveRightToVote: TypedContractMethod<
    [voter: AddressLike],
    [void],
    "nonpayable"
  >;

  proposalsCount: TypedContractMethod<[], [bigint], "view">;

  vote: TypedContractMethod<[proposal: BigNumberish], [void], "nonpayable">;

  voters: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, boolean, string, bigint] & {
        weight: bigint;
        voted: boolean;
        delegate: string;
        vote: bigint;
      }
    ],
    "view"
  >;

  winnerName: TypedContractMethod<[], [string], "view">;

  winnerProposal: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "chairperson"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "delegate"
  ): TypedContractMethod<[to: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getProposal"
  ): TypedContractMethod<
    [index: BigNumberish],
    [[string, bigint] & { name: string; voteCount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProposals"
  ): TypedContractMethod<[], [NebulaBallot.ProposalStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getVoter"
  ): TypedContractMethod<
    [account: AddressLike],
    [
      [bigint, boolean, string, bigint] & {
        weight: bigint;
        voted: boolean;
        delegateAddr: string;
        votedProposal: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "giveRightToVote"
  ): TypedContractMethod<[voter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "proposalsCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<[proposal: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "voters"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, boolean, string, bigint] & {
        weight: bigint;
        voted: boolean;
        delegate: string;
        vote: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "winnerName"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "winnerProposal"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "RightGranted"
  ): TypedContractEvent<
    RightGrantedEvent.InputTuple,
    RightGrantedEvent.OutputTuple,
    RightGrantedEvent.OutputObject
  >;
  getEvent(
    key: "VoteDelegated"
  ): TypedContractEvent<
    VoteDelegatedEvent.InputTuple,
    VoteDelegatedEvent.OutputTuple,
    VoteDelegatedEvent.OutputObject
  >;
  getEvent(
    key: "Voted"
  ): TypedContractEvent<
    VotedEvent.InputTuple,
    VotedEvent.OutputTuple,
    VotedEvent.OutputObject
  >;

  filters: {
    "RightGranted(address,uint256)": TypedContractEvent<
      RightGrantedEvent.InputTuple,
      RightGrantedEvent.OutputTuple,
      RightGrantedEvent.OutputObject
    >;
    RightGranted: TypedContractEvent<
      RightGrantedEvent.InputTuple,
      RightGrantedEvent.OutputTuple,
      RightGrantedEvent.OutputObject
    >;

    "VoteDelegated(address,address)": TypedContractEvent<
      VoteDelegatedEvent.InputTuple,
      VoteDelegatedEvent.OutputTuple,
      VoteDelegatedEvent.OutputObject
    >;
    VoteDelegated: TypedContractEvent<
      VoteDelegatedEvent.InputTuple,
      VoteDelegatedEvent.OutputTuple,
      VoteDelegatedEvent.OutputObject
    >;

    "Voted(address,uint256,uint256)": TypedContractEvent<
      VotedEvent.InputTuple,
      VotedEvent.OutputTuple,
      VotedEvent.OutputObject
    >;
    Voted: TypedContractEvent<
      VotedEvent.InputTuple,
      VotedEvent.OutputTuple,
      VotedEvent.OutputObject
    >;
  };
}
